version: '3.6'
services:
  redis:
    restart: always
    image: 'bitnami/redis:latest'
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
  app:
    restart: always
    build:
      context: ./webclient
      dockerfile: Dockerfile.dev
    volumes:
      - ./webclient/src:/app/src:ro
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.routers.app.entrypoints=web"
  api:
    restart: always
    env_file:
      - .env
    build: ./
    command: "/start-reload.sh"
    environment:
      JWT_SECRET_KEY: "NotAProdSecret"
    volumes:
      - ./aiplayground:/app/aiplayground:ro
    ports:
      - 8000:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api/v1`, `/socket.io/`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.middlewares.api.stripprefix.prefixes=/api/v1"
      - "traefik.http.routers.api.middlewares=api"

  traefik:
    image: "traefik:v2.3"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
